Add support for tmux
iam4x/zsh-iterm-touchbar pull request #10
Opened 2017-08-19 09:33 UTC by Hermanverschooten

When you start a TMUX session, none of the functions will work.
This is because TMUX swallows all unknown escape sequences.
To allow the sequence to pass through you need to surround it with:
`\ePtmux;\e<your original sequence>\e\\`

So I replaced all echo statements with a function that will check if we're in a TMUX session and do this.

2017-08-21 09:16 UTC, iam4x requested changes
Hey @Hermanverschooten 

Thank you very much for the contribution, I have just two little remarks and then it will be good to merge 👍 

This rock 👌

2017-08-21 09:16 UTC, iam4x commented on zsh-iterm-touchbar.plugin.zsh
> +  # echo -ne "\033]1337;PopKeyLabels\a"
Can we remove this commented line?

2017-08-21 09:16 UTC, iam4x commented on zsh-iterm-touchbar.plugin.zsh
> +add-zsh-hook precmd precmd_iterm_touchbar
Missing EOF breakline

2017-08-23 09:26 UTC, Hermanverschooten commented on zsh-iterm-touchbar.plugin.zsh
> +add-zsh-hook precmd precmd_iterm_touchbar
Should be fixed now

2017-08-23 09:31 UTC, iam4x approved these changes

2017-08-23 09:31 UTC, merged

2017-08-23 09:31 UTC, iam4x commented
Thanks 🚢